# Generated by Django 4.2.23 on 2025-12-19 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('alert_radius', models.FloatField(default=5.0, help_text='Alert radius in kilometers')),
                ('default_zoom', models.FloatField(default=15.0, help_text='Default map zoom level')),
                ('location_icon', models.CharField(default='assets/fun_icons/icon1.png', max_length=255)),
                ('push_notifications', models.BooleanField(default=True)),
                ('proximity_alerts', models.BooleanField(default=True)),
                ('sound_vibration', models.BooleanField(default=True)),
                ('anonymous_reporting', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'User Preference',
                'verbose_name_plural': 'User Preferences',
                'ordering': ['-updated_at'],
            },
        ),
    ]
