# Generated by Django 4.2.23 on 2025-12-19 17:17

from django.db import migrations, models
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0002_userpreferences'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='safezone',
            name='user_settin_device__08fbd8_idx',
        ),
        migrations.AlterField(
            model_name='safezone',
            name='device_id',
            field=encrypted_model_fields.fields.EncryptedCharField(),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='device_id',
            field=encrypted_model_fields.fields.EncryptedCharField(unique=True),
        ),
        migrations.AlterField(
            model_name='userdevice',
            name='fcm_token',
            field=encrypted_model_fields.fields.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='userpreferences',
            name='device_id',
            field=encrypted_model_fields.fields.EncryptedCharField(db_index=True, unique=True),
        ),
        migrations.AddIndex(
            model_name='safezone',
            index=models.Index(fields=['is_active'], name='user_settin_is_acti_89ae5f_idx'),
        ),
    ]
