# Generated by Django 4.2.23 on 2025-12-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_settings', '0003_remove_safezone_user_settin_device__08fbd8_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='safezone',
            name='device_id_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userdevice',
            name='device_id_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='userpreferences',
            name='device_id_hash',
            field=models.CharField(db_index=True, default='', max_length=64),
        ),
        migrations.AddIndex(
            model_name='safezone',
            index=models.Index(fields=['device_id_hash'], name='user_settin_device__6c9f04_idx'),
        ),
        migrations.AddIndex(
            model_name='userdevice',
            index=models.Index(fields=['device_id_hash'], name='user_settin_device__543eed_idx'),
        ),
        migrations.AddIndex(
            model_name='userpreferences',
            index=models.Index(fields=['device_id_hash'], name='user_settin_device__828690_idx'),
        ),
    ]
