# Generated by Django 4.2.23 on 2025-12-19 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(db_index=True, help_text='ISO 3166-1 alpha-2 country code (e.g., US, GH, NG)', max_length=2)),
                ('name', models.CharField(max_length=200)),
                ('service_type', models.CharField(choices=[('police', 'Police Station'), ('hospital', 'Hospital'), ('fireStation', 'Fire Station'), ('ambulance', 'Ambulance')], db_index=True, max_length=20)),
                ('phone_number', models.CharField(max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('hours', models.CharField(blank=True, help_text='Operating hours (e.g., "24/7", "9AM-5PM")', max_length=100, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['country_code', 'service_type', 'name'],
                'indexes': [models.Index(fields=['country_code', 'service_type'], name='emergency_s_country_b0f2bf_idx'), models.Index(fields=['is_active'], name='emergency_s_is_acti_0a7380_idx'), models.Index(fields=['latitude', 'longitude'], name='emergency_s_latitud_318f8c_idx')],
            },
        ),
    ]
