# Generated by Django 4.2.23 on 2025-12-22 22:31

from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incident_reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', encrypted_model_fields.fields.EncryptedCharField()),
                ('device_id_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('total_points', models.IntegerField(default=0)),
                ('reports_count', models.IntegerField(default=0)),
                ('confirmations_count', models.IntegerField(default=0)),
                ('current_tier', models.IntegerField(default=1)),
                ('verified_reports', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-total_points'],
                'indexes': [models.Index(fields=['-total_points'], name='scoring_use_total_p_069d2c_idx'), models.Index(fields=['current_tier'], name='scoring_use_current_74349d_idx')],
            },
        ),
        migrations.CreateModel(
            name='IncidentConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', encrypted_model_fields.fields.EncryptedCharField()),
                ('device_id_hash', models.CharField(db_index=True, max_length=64)),
                ('confirmed_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='confirmations', to='incident_reporting.incident')),
            ],
            options={
                'ordering': ['-confirmed_at'],
                'indexes': [models.Index(fields=['incident', '-confirmed_at'], name='scoring_inc_inciden_0888f4_idx')],
                'unique_together': {('incident', 'device_id_hash')},
            },
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge_type', models.CharField(choices=[('first_responder', 'First Responder'), ('truth_triangulator', 'Truth Triangulator'), ('night_owl', 'Night Owl'), ('accuracy_ace', 'Accuracy Ace')], max_length=50)),
                ('earned_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='scoring.userprofile')),
            ],
            options={
                'ordering': ['-earned_at'],
                'indexes': [models.Index(fields=['profile', 'badge_type'], name='scoring_bad_profile_fd7175_idx')],
                'unique_together': {('profile', 'badge_type')},
            },
        ),
    ]
