# Generated by Django 4.2.23 on 2025-12-20 22:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('incident_reporting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('alert_type', models.CharField(choices=[('highRisk', 'High Risk'), ('theft', 'Theft'), ('eventCrowd', 'Event Crowd'), ('trafficCleared', 'Traffic Cleared')], default='highRisk', max_length=50)),
                ('severity', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low'), ('info', 'Info')], default='medium', max_length=20)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.IntegerField(blank=True, default=0, null=True)),
                ('distance_meters', models.FloatField(blank=True, help_text='Distance from user location in meters', null=True)),
                ('incident', models.ForeignKey(help_text='The incident that triggered this alert', on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='incident_reporting.incident')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='alerts_aler_timesta_0459bf_idx'), models.Index(fields=['severity'], name='alerts_aler_severit_202179_idx'), models.Index(fields=['alert_type'], name='alerts_aler_alert_t_e287ad_idx')],
            },
        ),
    ]
