name: Feature Request
description: Suggest a new feature for SafeZone
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the sections below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve?
      placeholder: Is your feature request related to a problem? Describe it.
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like
      placeholder: A clear description of what you want to happen
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Any alternative solutions or features you've considered?
    validations:
      required: false

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which part of the app would this affect?
      options:
        - Frontend (Flutter)
        - Backend (Django)
        - Both
        - New component
    validations:
      required: true

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to work on this feature?
      options:
        - label: I would like to work on this feature
          required: false
