# Generated by Django 4.2.23 on 2025-12-19 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('accident', 'Accident'), ('fire', 'Fire'), ('theft', 'Theft'), ('suspicious', 'Suspicious Activity'), ('lighting', 'Lighting Issue'), ('assault', 'Assault'), ('vandalism', 'Vandalism'), ('harassment', 'Harassment'), ('roadHazard', 'Road Hazard'), ('animalDanger', 'Animal Danger'), ('medicalEmergency', 'Medical Emergency'), ('naturalDisaster', 'Natural Disaster'), ('powerOutage', 'Power Outage'), ('waterIssue', 'Water Issue'), ('noise', 'Noise Complaint'), ('trespassing', 'Trespassing'), ('drugActivity', 'Drug Activity'), ('weaponSighting', 'Weapon Sighting')], max_length=50)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('confirmed_by', models.IntegerField(default=1)),
                ('notify_nearby', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['-timestamp'], name='incident_re_timesta_d70423_idx'), models.Index(fields=['category'], name='incident_re_categor_330f61_idx')],
            },
        ),
    ]
