# Generated by Django 4.2.23 on 2025-12-23 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incident_reporting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='reporter_device_id_hash',
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
