# Generated by Django 4.2.23 on 2025-12-19 17:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmergencyContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', encrypted_model_fields.fields.EncryptedCharField()),
                ('name', encrypted_model_fields.fields.EncryptedCharField()),
                ('phone_number', encrypted_model_fields.fields.EncryptedCharField()),
                ('email', encrypted_model_fields.fields.EncryptedCharField(blank=True, null=True)),
                ('relationship', models.CharField(choices=[('family', 'Family'), ('friend', 'Friend'), ('colleague', 'Colleague'), ('neighbor', 'Neighbor'), ('other', 'Other')], default='other', max_length=20)),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='emergency_contacts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['priority', '-created_at'],
                'indexes': [models.Index(fields=['is_active'], name='emergency_c_is_acti_da322f_idx'), models.Index(fields=['priority'], name='emergency_c_priorit_dc466f_idx')],
            },
        ),
    ]
