# Generated by Django 4.2.23 on 2025-12-19 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Guide',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('section', models.CharField(choices=[('how_it_works', 'How SafeZone Works'), ('reporting', 'Reporting Incidents'), ('alerts', 'Understanding Alerts'), ('trust_score', 'Trust Score System'), ('privacy', 'Privacy & Data Protection'), ('best_practices', 'Safety Best Practices'), ('emergency', 'Emergency Features'), ('getting_started', 'Getting Started')], max_length=50)),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('icon', models.CharField(blank=True, max_length=100, null=True)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['section', 'order'],
                'indexes': [models.Index(fields=['section', 'order'], name='guides_guid_section_35f8e3_idx'), models.Index(fields=['is_active'], name='guides_guid_is_acti_89760a_idx')],
            },
        ),
    ]
